fin = open ('paint.in', 'r')
fout = open ('paint.out', 'w')
a,b = list(map(int, fin.readline().split()))
c,d = list(map(int, fin.readline().split()))
AB = list(range(a, b))
CD = list(range(c, d))
my_set = set(AB+CD)
fout.write(str(len(my_set)))
fin.close()
fout.close()
